### ISSUE TITLE
5.3 build error

### ISSUE THREAD

**Issue by ectomia** [kostenickj/UE5_SimpleGroomExporter#1]
HI just tried this in UE5.3 and had the build type issue pop up

Is there another file I need to put somewhere? I can see theres a fix in the private folder but replaced the file inside directory with it and still this pops [up[](url)](![error](https://github.com/kostenickj/UE5_SimpleGroomExporter/assets/127079647/871d1c91-fbb6-4589-8fe4-dfb34a2977d5))

**Comment by ectomia** [comment]
Attempted to rebuild for 5.3 and still get the same error

**Comment by kostenickj** [comment]
ill take a look at this, i only tested on 5.4 but i should be able to get it to compile on 5.3 as well

**Comment by kostenickj** [comment]
I just built it for 5.3 and it compiles fine. I uploaded the binaries to the discord server. You can find the link in the readme

**Comment by ectomia** [comment]
Worked fine. Many thanks for this its much appreciated. Keep up the good work with the tutorials they are brilliant
